### ISSUE TITLE
Probably reduce memory usage

### ISSUE THREAD

**Issue by vnepogodin** [ArthurSonzogni/FTXUI#290] opened 2021-12-29 22:18 UTC
example "homescreen" uses around ~150MB of virtual memory
example "gallery" uses around ~79MB of virtual memory

I wonder is it possible to reduce virt memory usage?

**Comment by ArthurSonzogni** [comment] 2021-12-29 23:17
It sounds like way too much! How big is your terminal dimensions? Are you on Linux?
I will take a look and verify how much is needed.

**Comment by ArthurSonzogni** [comment] 2021-12-29 23:36
I took a look. Note that this is virtual memory, not residential memory. This means the program has some address space in its memory map, but it isn't used, and it doesn't take any space out of the RAM.

I tried "homescreen" and it only uses 4.7 Mo (4706 Ko).
However its virtual one is indeed 151MB as you said

![image](https://user-images.githubusercontent.com/4759106/147710418-bf5b57a6-e408-42a5-abeb-3e0bebf9d626.png)

I admit I don't know why the virtual memory is high compared to the real memory used. Do you have ideas? Would you know why we should care?

**Comment by vnepogodin** [comment] 2021-12-30 17:06
> It sounds like way too much! How big is your terminal dimensions? Are you on Linux? I will take a look and verify how much is needed.

was 136 columns then I was testing. Using Arch Linux

**Comment by vnepogodin** [comment] 2021-12-31 11:03
btw I made it faster a bit, but memory usage is changed
![image](https://user-images.githubusercontent.com/37552959/147819859-e637e40d-014d-48a9-b956-a124d8a44a7a.png)

**Comment by ArthurSonzogni** [comment] 2022-01-01 18:03
@vnepogodin Thanks for taking a look.
If you manage the find the root cause of this virtual memory usage, please let me know.
I suspect this is the way the allocator works. It request a lot of addressable space, without committing any data to it.

**Comment by vnepogodin** [comment] 2022-03-14 20:00
Update:
Memory usage is changed after introducing animation and other cool features
I think that virtual memory usage is high because of how `shared_ptr`s works :eyes: 
![image](https://user-images.githubusercontent.com/37552959/158251069-993033bb-2c38-4fd4-88bf-1dfacfe732a8.png)

**Comment by ArthurSonzogni** [comment] 2022-03-15 20:09
Thanks for checking it!

I honestly don't have any idea what is going on. If the problem was about some `shared_ptr` cycle unable to deallocate, we would have seen the residential memory to increase.

I checked running valgrind:
```
==7396== HEAP SUMMARY:
==7396==     in use at exit: 0 bytes in 0 blocks
==7396==   total heap usage: 20,803 allocs, 20,803 frees, 8,259,369 bytes allocated
==7396== 
==7396== All heap blocks were freed -- no leaks are possible
==7396== 
==7396== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

Things seems okay.

**Comment by vnepogodin** [comment] 2022-03-19 22:02
Yeah I have no problem about that.
```
==45685== HEAP SUMMARY:
==45685==     in use at exit: 0 bytes in 0 blocks
==45685==   total heap usage: 39,077 allocs, 39,077 frees, 44,362,563 bytes allocated
==45685==
==45685== All heap blocks were freed -- no leaks are possible
==45685==
==45685== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

I guessing that it could be `shared_ptr` have too many references

**Comment by ArthurSonzogni** [comment] 2022-03-20 15:02
> I guessing that it could be shared_ptr have too many references

No, I don't believe it. It would use resident memory instead. Unreacheable memory would be shown as a memory leak by valgrind.

I believe somehow (?), the allocator has issues.

**Comment by MattBystrin** [comment] 2022-03-21 18:28
> I guessing that it could be shared_ptr have too many references
Well this can cause one interesting effect. Memory frees after all references are unlinked. What if somewhere unwanted references are kept ? So our object wil still present in a heap, and vallgrind will also say that everythink is OK. Is it possible ?

**Comment by ArthurSonzogni** [comment] 2022-03-21 19:07
> What if somewhere unwanted references are kept ?
They would use resident memory, not virtual memory.

I tried proxying calls to the allocator to check there was no logic requesting GB of memory. I did not found anything.

**Comment by vnepogodin** [comment] 2022-06-13 00:02
> > What if somewhere unwanted references are kept ?
> > They would use resident memory, not virtual memory.
> 
> I tried proxying calls to the allocator to check there was no logic requesting GB of memory. I did not found anything.

I might found something interesting. Why it does many temporarly allocations of the text?
pre-last = Allocations; last = Temporary

gallery:
![image](https://user-images.githubusercontent.com/37552959/173258728-bbd109ed-fdee-4d4a-bf4b-e61d29af0acd.png)
homescreen:
![image](https://user-images.githubusercontent.com/37552959/173258801-dda127f4-4d40-4d6e-bbce-163d301b5be1.png)

Also, is it necessary to allocate many times?
![image](https://user-images.githubusercontent.com/37552959/173258843-2119585b-3e38-4c76-ad57-5755ef649b66.png)

I got that data from HeapTrack tool.
```bash
heaptrack ./build/examples/component/ftxui_example_gallery
heaptrack ./build/examples/component/ftxui_example_homescreen
```

**Comment by ArthurSonzogni** [comment] 2022-06-13 11:47
Nice! I didn't knew about heaptrack. That's a great discovery!

**Comment by vnepogodin** [comment] 2022-06-14 22:43
> Nice! I didn't knew about heaptrack. That's a great discovery!

Thanks for taking a look! The temp allocations reduced. but still exist as you can see on the screenshot
![image](https://user-images.githubusercontent.com/37552959/173700272-2d43bddd-5e3b-46b0-b699-3d83599d5bcb.png)

And according to the tool it still exists as location with the biggest amount of temp allocations:
![image](https://user-images.githubusercontent.com/37552959/173700526-5ea963a8-f9c2-4360-b563-90bd7c9127f7.png)

Here is the data which you can run with:
```bash
heaptrack --analyze "heaptrack.ftxui_example_homescreen.225161.zst"
```
here is the file: https://cloud.ptr1337.dev/s/HqTJbiRrYCq6j5E
##### note: GitHub doesn't support that file type, so I uploaded to the cloud

I'll also take a look how it can be reduced even more

**Comment by ArthurSonzogni** [comment] 2023-01-07 17:22
I think we can close this.

I checked today on the homescreen example. There are about 700kB memory usage and 1400kb peak.

**Closed by ArthurSonzogni** 2023-01-07 17:22 UTC
